"""empty message

Revision ID: ea4c1413adfc
Revises: 8c590271e2a0
Create Date: 2022-12-06 21:58:58.196295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4c1413adfc'
down_revision = '8c590271e2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokedex', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('pokedex_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['entry'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokedex', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('pokedex_name_key', ['name'])
        batch_op.drop_column('entry')

    # ### end Alembic commands ###
